'use client'

import type { Metadata } from 'next';
import '@fontsource-variable/nunito';
import '../app/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import { StarWarsFilms } from '@/lists/StarwarsFilms'
import { ListMaker } from '@/components/ListMaker';

const Starwars = () => {
    
    return (
        <div>
            <ListMaker list={StarWarsFilms} />
        </div>
    )
}

export default Starwars 